// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package dependency_injection

import (
	"database/sql"
	"github.com/bwmarrin/snowflake"
	"github.com/lopysso/server/config"
	config2 "github.com/lopysso/server/service/config"
	"github.com/lopysso/server/service/mysql"
	"github.com/lopysso/server/service/number_generator"
)

// Injectors from config.go:

func InjectConfig() config.Config {
	configConfig := config2.ConfigInstance()
	return configConfig
}

// Injectors from mysql.go:

func InjectMysql() *sql.DB {
	configConfig := InjectConfig()
	db := mysql.MysqlInstance(configConfig)
	return db
}

// Injectors from number_generator.go:

func InjectSnowflakeNode() *snowflake.Node {
	configConfig := InjectConfig()
	node := number_generator.InstanceSnowflakeNode(configConfig)
	return node
}
